### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by AleksES** [gnarf/jquery-requestAnimationFrame#13]
Hello, gnarf.

NIce extension, but bower doesn't know it :) Let you fix it.

**Comment by rulin132** [comment]
+1

Until then, you can let bower handle this package this way:

```
bower install https://github.com/gnarf/jquery-requestAnimationFrame.git
```

**Comment by AleksES** [comment]
@rulin132 yeah, I know this way :)
But as I understood - owner doesn't support repo anymore...
